ARG IGNITION_VERSION="8.1.28"
FROM inductiveautomation/ignition:${IGNITION_VERSION:-latest}

USER root

ENV WORKING_DIRECTORY ${WORKING_DIRECTORY:-/workdir}
ENV ACCEPT_IGNITION_EULA "Y"
ENV GATEWAY_ADMIN_USERNAME ${GATEWAY_ADMIN_USERNAME:-admin}
ENV GATEWAY_ADMIN_PASSWORD ${GATEWAY_ADMIN_PASSWORD:-password}
ENV IGNITION_EDITION ${IGNITION_EDITION:-standard}
ENV GATEWAY_MODULES_ENABLED ${GATEWAY_MODULES_ENABLED:-alarm-notification,allen-bradley-drivers,bacnet-driver,opc-ua,perspective,reporting,tag-historian,web-developer}
ENV IGNITION_UID ${IGNITION_UID:-1000}
ENV IGNITION_GID ${IGNITION_GID:-1000}
ENV DEVELOPER_MODE ${DEVELOPER_MODE:-N}
ENV ENABLE_LOCALTEST_ADDRESS ${ENABLE_LOCALTEST_ADDRESS:-Y}
ENV GATEWAY_PUBLIC_ADDRESS ${GATEWAY_PUBLIC_ADDRESS:-localhost}
ENV GATEWAY_PUBLIC_HTTP_PORT ${GATEWAY_PUBLIC_HTTP_PORT:-8088}
ENV GATEWAY_PUBLIC_HTTPS_PORT ${GATEWAY_PUBLIC_HTTPS_PORT:-8043}
ENV DISABLE_QUICKSTART ${DISABLE_QUICKSTART:-true}

ENV SYMLINK_GITIGNORE ${SYMLINK_GITIGNORE:-true}
ENV SYMLINK_LOGBACK ${SYMLINK_LOGBACK:-true}
ENV SYMLINK_PROJECTS ${SYMLINK_PROJECTS:-true}
ENV SYMLINK_THEMES ${SYMLINK_THEMES:-true}
ENV ADDITIONAL_DATA_FOLDERS ${ADDITIONAL_DATA_FOLDERS:-}

# Setup dedicated user
RUN groupmod -g ${IGNITION_GID} ignition && \
    usermod -u ${IGNITION_UID} ignition && \
    chown -R ${IGNITION_UID}:${IGNITION_GID} /usr/local/bin/

# Check if any of the symlinks are enabled, if so, create the working directory
RUN if [ "$SYMLINK_LOGBACK" = "true" ] || [ "$SYMLINK_PROJECTS" = "true" ] || [ "$SYMLINK_THEMES" = "true" ]; then \
    mkdir -p ${WORKING_DIRECTORY} && \
    chown -R  ${IGNITION_UID}:${IGNITION_GID} ${WORKING_DIRECTORY}; \
    fi
    
# Copy gitignore into the working
COPY --chown=${IGNITION_UID}:${IGNITION_GID} ./seed-contents/ /usr/local/bin/seed-contents/
COPY --chmod=0755 --chown=${IGNITION_UID}:${IGNITION_GID} ./entrypoint-shim.sh /usr/local/bin/

USER ${IGNITION_UID}:${IGNITION_GID}

ENTRYPOINT [ "entrypoint-shim.sh" ]