on:
  workflow_dispatch:

jobs:  
  build-iiot-images:
    name: "Build IIOT Images"
    # needs: run-checks
    uses: ./.github/workflows/multi-arch-build.yml
    with:
      PUSH: true
      TARGET: "ignition-iiot"
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}